mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views.
"""
from django.conf.urls import include, url
from django.contrib import admin

from . import views
#from recommender import views as rec_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
#    url(r'^login/', views.login, name='login'),
#    url(r'^register/', rec_views.register, name='register'),
    url(r'^recommender/', include('recommender.urls')),
]

qf_site/urls.py
"""qf_site URL Configuration

The `urlpatterns` list routes URLs to views.
"""
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
#    url(r'^login/', views.login, name='login'),
#    url(r'^register/', rec_views.register, name='register'),
    url(r'^recommender/', include('recommender.urls')),
]

recommender/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'recommender'
urlpatterns = [
    url(r'^$', views.index, name='index'), # can also pass kwargs={...}
    url(r'^profile/$', views.profile, name='profile'),
#    url(r'^history/(?P<page_number>[0-9]+)$', views.history, name='history'),
    url(r'^history/$', views.history, name='history'),
    url(r'^eat/(?P<food_ID>[0-9]+)$', views.eat_ID, name='eat_ID'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', auth_views.login, {'redirect_field_name': 'recommender/index.html'}),
    url(r'^accounts/logout/$', auth_views.logout_then_login), #{'login_url': '/accounts/login'}),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/complete/$', views.registration_complete, name='registration_complete'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^plot_history.png$', views.plot_history, name='plot_history')
]

recommender/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User  # django built-in User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    food_history = JSONField(default=list(), blank=True)

    def __repr__(self):
        return(self.food_history)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    
class Food(models.Model):
#    id = models.IntegerField(primary_key=True)
    id_string = models.CharField(max_length=20)
    name = models.CharField(max_length=200)
    recipe_yield = models.CharField(max_length=20)
    servings = models.CharField(max_length=20)
    url = models.CharField(max_length=200)
    ingredients = JSONField(default=dict())
    nutrients = JSONField(default=dict())
#    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __repr__(self):
        return(self.name)        

#class User(models.Model):
# #   id = models.IntegerField(primary_key=True)
#    name = models.CharField(max_length=200)
#    join_date = models.DateTimeField('Date joined')
#    
#    def joined_recently(self):
#        return self.join_date >= timezone.now() - datetime.timedelta(weeks=1)
#    def __repr__(self):
#        return(self.name)

qf_site/views.py
from django.shortcuts import render, redirect, render_to_response
# from django.http import HttpResponse

def index(request):
    # return HttpResponse("Welcome to Quantifood.")
    return(redirect('recommender:index'))

#def login(request):
#    return HttpResponse("Login form")
#
#def register(request):
#    return HttpResponse("Register form")
#    

recommender/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.core.cache import cache

import matplotlib
matplotlib.use('Agg')
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from .helpers import *


@login_required
def index(request):
    if cache.get('recipe_ids') is not None:
        recipe_ids = cache.get('recipe_ids')
        recipe_matrix = cache.get('recipe_matrix')
    else:
        recipe_ids, recipe_matrix = get_recipe_matrix(loc='static')
        cache.set_many({'recipe_ids': recipe_ids, 'recipe_matrix': recipe_matrix}, None)
    u = request.user
    if cache.get('target') is not None:
        cached = cache.get_many(['target', 'best_IDs', 'best_ratings'])
        target, best_IDs, best_ratings = cached['target'], cached['best_IDs'], cached['best_ratings']
    else:
        target = update_target(initial_target, recipe_ids, recipe_matrix, u)
        ratings = rate_recipes(recipe_matrix, target)
        best_IDs, best_ratings = recommend_foods(ratings)
        cache.set_many({'target': target, 'best_IDs': best_IDs,
                        'best_ratings': best_ratings}, None)
    best_names, best_urls = [], []
    for ID in best_IDs:
        best_names.append(Food.objects.get(id_string=ID).name)
        best_urls.append(Food.objects.get(id_string=ID).url)
    best = zip(best_IDs, best_ratings, best_names, best_urls)
    context = {'best': best, 'target': target}
    return (render(request, 'recommender/index.html', context))


@login_required
def profile(request):
    prefs = {}
    preferences = {'Disabilities':'Lvl5 vegan - can not eat anything that casts a shadow', 
                 'Banned foods': 'Bacon, Cheese',
                 'Allergies': 'Fish, Milk'
                 }
    prefs['Placeholder preferences'] = preferences
    context = {'prefs': prefs}
    return(render(request, 'recommender/profile.html', context))


@login_required
def history(request):
    u = request.user
    history = u.profile.food_history
    foodnames = []
    if len(history) > 0:
        for ID in history:
            foodnames.append(Food.objects.get(id_string=ID).name)
    context = {'foodnames': foodnames, 'history': history}
    return(render(request, 'recommender/history.html', context))


@login_required
def plot_history(request):
    u = request.user
    if cache.get('recipe_ids') is not None:
        recipe_ids = cache.get('recipe_ids')
        recipe_matrix = cache.get('recipe_matrix')
    else:
        recipe_ids, recipe_matrix = get_recipe_matrix(loc='static')
        cache.set_many({'recipe_ids': recipe_ids, 'recipe_matrix': recipe_matrix}, None)
    fig = plot_nutrient_history(u, recipe_ids, recipe_matrix)
    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type='image/png')
    canvas.print_png(response)
    return(response)


@login_required    
def eat_ID(request, food_ID):
    u = request.user
    u.profile.food_history.append(food_ID)
    u.save()
    cache.delete_many(['target', 'best_IDs', 'best_ratings'])
    return(redirect('recommender:history'))


@login_required
def reset(request):
    u = request.user
    u.profile.food_history = []
    u.save()
    cache.delete_many(['target', 'best_IDs', 'best_ratings'])
    return(redirect('recommender:index'))    


def register(request):
#    c = RequestContext(request, {})
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            u = form.save()
            return(redirect('recommender:registration_complete'))
    else:
        form = UserCreationForm()
    return(render(request, 'registration/register.html', {'form':form}))


def registration_complete(request):
    return(render(request, 'registration/registration_complete.html'))

recommender/templates/recommender/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'recommender/style.css' %}" />
<html>
  <head>
    <title>{{ title }} - QuantiFood</title>
  </head>
  <body>
	<div>
	<a href="{% url 'recommender:index' %}"><img src="{% static 'recommender/images/logo.png' %}" alt="QuantiFood" width="256" height="100"> Home</a>
	{% if user.is_authenticated %}
	| <a href="{% url 'recommender:history' %}">My History</a>
	| <a href="{% url 'recommender:profile' %}">My Profile</a>
	| <a href="{% url 'recommender:logout' %}?next=/">Log out</a>
	{% endif %}
	{% if not user.is_authenticated %}
	| <a href="{% url 'recommender:login' %}">Log in</a>
	| <a href="{% url 'recommender:register' %}">Register</a>
	| <a href="{% url 'admin:index' %}">Admin</a>
	{% endif %}
    </div>
    <hr>
    {% block content %}
	{% endblock %}
  </body>
</html>

recommender/templates/recommender/history.html
{% extends 'recommender/base.html' %}
{% load staticfiles %}
{% block content %}
{% if foodnames %}
	<h3>You have eaten these servings today, {{ user.username }}:</h3>
    <ul>
    {% for food in foodnames %}
	<li> {{ food }} </li>
    {% endfor %}
    </ul>
	<br><br>
	<h3><a href="{% url 'recommender:index' %}">Eat another serving</a></h3>
	<h3><a href="{% url 'recommender:plot_history' %}" target="_blank">Show your nutritional progress</a></h3>
	<h3><a href="{% url 'recommender:reset' %}">Reset your food history</a></h3>
	<br><br>
	<!-- <img src="{% static 'recommender/images/history.png' %}" alt="Food history" width="900" height="600"> -->
{% else %}
    <p>No food history yet. Go <a href="{% url 'recommender:index' %}">Home</a> and eat something!</p>
{% endif %}
<br><br>
<!-- {{ nutrient_history }} -->
{% endblock %}

recommender/templates/recommender/index.html
{% extends 'recommender/base.html' %}
{% block content %}
 <h3>What would you like to eat today, {{ user.username }}?</h3>
{% if user.is_authenticated %}
{% if best %}
    <ul>
    {% for items in best %}
        <!-- <li><a href="/history/{{ food.id }}/">{{ food.name }}</a></li> -->
		<li><a href="{% url 'recommender:eat_ID' items.0 %}">Eat a serving </a> of {{ items.1 }} % rated: <a href={{ items.3 }}>{{ items.2 }}</a> ({{ items.0 }})</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recommendations available.</p>
{% endif %}
{% endif %}
<br>
<!-- {{ target }} -->
<br>
{% if not user.is_authenticated %}
<p> Please log in to view nutrient-optimized recommendations for You.</p>
{% endif %}
{% endblock %}

<!-- 
 <p><a href="{% url 'recommender:index' %}">Home</a></p>
 <p><a href="{% url 'recommender:profile' %}">Profile</a></p>
 <p><a href="{% url 'recommender:history' %}">Food History</a></p>
 -->

recommender/templates/recommender/profile.html
{% extends 'recommender/base.html' %}
{% block content %}
{% if prefs %}
    <ul>
    {% for key, val in prefs.items %}
		<h3>{{ key }}</h3>
		{% for key2, val2 in val.items %}
			<li>{{ key2 }}: {{ val2 }}</li>
		{% endfor %}
    {% endfor %}
    </ul>
{% else %}
    <p>No preferences.</p>
{% endif %}
{% endblock %}